1.0:
  Sequencing Sample ID: 0
  Sequencing Technology: 1
  Customer Sample ID: 2
  Customer Subject ID: 3
  Gender: 4
  Sample Type: 5
  Sample Source: 6
  Tumor Status: 7
  Mother's Subject ID: 8
  Father's Subject ID: 9
  Monozygotic Twin Subject ID: 10
  Affected Status: 11
  Comments: 12
  Spouse Subject ID: 13
  Spouse Order: 14
  Child Order: 15
